Main svc
ArseniiYanovskyi/java-explore-with-me pull request #4
Opened 2023-11-06 11:09 UTC by ArseniiYanovskyi

2023-11-06 17:47 UTC, Yang-Pi requested changes
Общий комментарий про пакеты: admin, private, public - это о домене; controller, dao... - это о сущностях; сейчас оба подхода смешались, но нужно следовать только одному

2023-11-06 17:47 UTC, Yang-Pi commented on ewm_service/src/main/java/ru/practicum/admin_package/controller/AdminController.java
> +package ru.practicum.admin_package.controller;
суффикс _package лучше удалить, не совсем понятный паттерн названия

2023-11-06 17:47 UTC, Yang-Pi commented on ewm_service/src/main/java/ru/practicum/admin_package/controller/AdminController.java
> +    public CategoryDto addCategory(@RequestBody CategoryDto categoryDto) {
Для методов POST имеет смысл добавить аннотацию @Valid для аргумента, те сделать валидации на уровне модели, а не сервиса и метода checkCategoryDto. Почему так будет лучше - сервис даже не вызовется, если придет неверное тело запроса, это именно вопрос оптимизации использования ресурсов

2023-11-06 17:47 UTC, Yang-Pi commented on ewm_service/src/main/java/ru/practicum/admin_package/controller/AdminController.java
> +@RequestMapping(path = "/admin")
Админский сервис было бы удачно разделить на несколько - categories, users, compilations, events; такая структура более удобна с точки зрения поддержки

2023-11-06 17:47 UTC, Yang-Pi commented on ewm_service/src/main/java/ru/practicum/admin_package/controller/AdminController.java
> +@RequestMapping(path = "/admin")
Это касается как контроллеров, так и сервисов

2023-11-06 17:47 UTC, Yang-Pi commented on ewm_service/src/main/java/ru/practicum/admin_package/service/utils/AdminServiceUtils.java
> +public class AdminServiceUtils {
А почему это утилитарный класс? В чем его идея?
Причем он создается в виде полноценного бина, те это отдельный объект. По описанным методам это скорее часть админского сервиса

2023-11-06 17:47 UTC, Yang-Pi commented on ewm_service/src/main/java/ru/practicum/private_package/controller/PrivateController.java
> +package ru.practicum.private_package.controller;
тоже нужно убрать _package из названия пакета

2023-11-06 17:47 UTC, Yang-Pi commented on ewm_service/src/main/java/ru/practicum/private_package/service/PrivateServiceImpl.java
> +        if (!newRequestConflictCheckResult.equals("ok")) {
1) Не самый удачный механизм - если метод вернул ok, то тогда..
а если метод перепишут и будут возвращать OK, то все будет успешно компилироваться, и даже работает верно, но вот это условие будет падать

поэтому результатом метода должен быть boolen

2) а почему конфликт? 409 ошибка это как-то жестко для случая, когда пытаются еще раз создать обхект, можешь просто возвращать уже имеющийся объект

2023-11-06 17:47 UTC, Yang-Pi commented on ewm_service/src/main/java/ru/practicum/private_package/service/PrivateServiceImpl.java
> +        utils.checkIsUserPresent(userId);
1 запрос к бд - checkIsUserPresent
2 запрос к бд - findByIdAndRequesterId

каждый запрос к бд имеет свою цену - ресурсы и время, поэтому важно ответить на вопрос: а можно ли сделать только один запрос вместо двух? в случае этого метода ответ - да, можно.

2023-11-08 15:36 UTC, ArseniiYanovskyi commented on ewm_service/src/main/java/ru/practicum/private_package/service/PrivateServiceImpl.java
> +        if (!newRequestConflictCheckResult.equals("ok")) {
Если программа будет возвращать другой код - тесты не будут проходится.

2023-11-08 15:37 UTC, ArseniiYanovskyi commented
Здравствуйте! я исправил работу следуя вашим комментариям, изменив структуру к "по сущностям". 
Про код ошибки 409, если программа будет возвращать другой код - тесты не будут проходится. 
Добавил аннотацию @Valid для методов POST и вовсе удалил класс-валидатор.
ServiceUtils я оставил, но значительно сократил его методы следуя двум условиям: 
1 - для избегания дубляжа кода в двух разных сервисах, 
2 - необходимо запросить количество просмотров у сервиса статистики.

2023-11-09 08:31 UTC, Yang-Pi approved these changes

2023-11-09 08:56 UTC, merged